services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eleve_api
    ports:
      - "${PORT:-3000}:3000"
      - "${DEBUG_PORT:-9229}:9229"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ["npm", "run", "start:dev"]
  db:
    image: postgres:17
    container_name: eleve_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./etc/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
